# Generated by Django 3.0.6 on 2020-05-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WechatMenuModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button', models.CharField(help_text='一级菜单可设置1~3个，每个菜单最多4个汉字', max_length=16, verbose_name='一级菜单')),
                ('sub_button', models.CharField(blank=True, help_text='二级菜单可设置1~5个，每个菜单最多7个汉字', max_length=28, null=True, verbose_name='二级菜单')),
                ('type', models.CharField(choices=[('click', '事件推送'), ('view', '跳转网页')], max_length=100, verbose_name='菜单类型')),
                ('reply_type', models.CharField(choices=[('text', '文字消息'), ('view', '图文消息')], max_length=100, verbose_name='回复的消息的类型')),
                ('key', models.CharField(blank=True, help_text='菜单的key值，', max_length=128, null=True, verbose_name='文字消息')),
                ('url', models.URLField(blank=True, help_text='菜单类型为跳转网页时必填', max_length=1024, null=True, verbose_name='图文消息')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'tb_wechat_menu',
            },
        ),
    ]
