# Generated by Django 3.0.6 on 2020-05-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatmenumodel',
            name='reply_type',
            field=models.CharField(choices=[('text', '文字消息'), ('view', 'url链接页面')], max_length=100, verbose_name='回复的消息的类型'),
        ),
    ]
