# Generated by Django 3.0.6 on 2020-05-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0002_auto_20200515_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechatmenumodel',
            name='key',
            field=models.CharField(blank=True, help_text='菜单的key值，', max_length=128, null=True, verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='wechatmenumodel',
            name='url',
            field=models.URLField(blank=True, help_text='菜单类型为view时必填', max_length=1024, null=True, verbose_name='url'),
        ),
    ]
