# Generated by Django 3.0.6 on 2020-05-15 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat', '0003_auto_20200515_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechatmenumodel',
            name='reply_type',
        ),
    ]
